# Generated by Django 5.1.4 on 2024-12-26 07:22

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.basemodel')),
                ('quantity', models.PositiveIntegerField()),
                ('is_order_placed', models.BooleanField(default=False)),
                ('cake_varient_object', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='store.cakevarient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shape_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shape')),
            ],
            bases=('store.basemodel',),
        ),
    ]
